main:
  clusterGroupName: datacenter

global:
  pattern: industrial-edge

  options:
    useCSV: False
    syncPolicy: Automatic
    installPlanApproval: Automatic

  imageregistry:
    account: luisarizmendi
    hostname: quay.io
    type: quay

  git:
    hostname: github.com
    account: luisarizmendi
    username: luisarizmendi
    email: luisarizmendi@redhat.com
    dev_revision: main

  s3:
    bucket:
      name: BUCKETNAME
      region: AWSREGION
      message:
        aggregation:
          count: 50
      custom:
        endpoint:
          enabled: false